name: flutter_video_meet
description: Starter app for video meeting assessment
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_riverpod: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.1.0
  flutter_native_splash: ^2.4.6



dev_dependencies:
  flutter_test:
   sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png


flutter_native_splash:
  color: "#071b5d"
  image: "assets/splash.png"
  android: true
  ios: true

android_12:
  image: assets/splash.png
  icon_background_color: "#000000"
  image_dark: assets/splash.png
  icon_background_color_dark: "#000000"




